apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notejam-jenkins
  template:
    metadata:
      labels:
        app: notejam-jenkins
    spec:
      containers:
        - name: app-jenkins
          image: janit31/my-notejam
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret-jenkins
                key: password
          - name: POSTGRES_HOST
            value: postgres-service-jenkins

---

apiVersion: v1
kind: Service
metadata:
  name: notejam-jenkins
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: notejam-jenkins
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notejam-jenkins
  annotations:
    ingressClassName: nginx
spec:
  rules:
    - host: notesapp-jenkins.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notejam-jenkins
                port:
                  number: 80
