apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-jenkins
  labels:
    name: my-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
