apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-jenkins
  template:
    metadata:
      labels:
        app: postgres-jenkins
    spec:
      containers:
      - name: postgres-jenkins
        image: postgres
        resources: {}
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret-jenkins
                key: password
          - name: POSTGRES_DB
            value: notejam
        volumeMounts:
        - name: postgres-volume-mount
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-volume-mount
        persistentVolumeClaim:
          claimName: postgres-pvc-jenkins
